# Generated by Django 4.2.11 on 2024-05-11 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('transaction_id', models.CharField(max_length=128)),
                ('service', models.CharField(choices=[('VENMO', 'Venmo'), ('PAYPAL', 'PayPal'), ('ZELLE', 'Zelle'), ('CHECK', 'Check')], max_length=128)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='invoice.invoice')),
            ],
        ),
    ]
