# Generated by Django 4.2.11 on 2024-05-08 07:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('transaction_id', models.CharField(max_length=128)),
                ('service', models.CharField(choices=[('VENMO', 'Venmo'), ('PAYPAL', 'PayPal'), ('ZELLE', 'Zelle'), ('CHECK', 'Check')], max_length=128)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='point_of_contact',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='client',
            name='person_of_contact',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='address_line1',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='client',
            name='address_line2',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='invoice.client'),
        ),
        migrations.DeleteModel(
            name='contact',
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='invoice.payment'),
        ),
    ]
