# Generated by Django 4.2.11 on 2024-05-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_payment_remove_client_point_of_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
